---
title: "R Markdown"
output:
  html_document:
    number_sections: false
    toc: no
---

```{r child = "knitr_setup.Rmd"}
```

The most comprehensive resource on working with R Markdown is the [Definitive Guide](https://bookdown.org/yihui/rmarkdown/).

For a quick reference guide that you can print out, check out the [Rstudio Rmarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf).

Here are some useful tools for learning and working with R Markdown:

- [60 second markdown guide](https://commonmark.org/help/)
- [10 minute markdown tutorial](https://commonmark.org/help/tutorial/)
- [Markdown It](https://markdown-it.github.io): Quickly demo Markdown code
- [Table generator](http://www.tablesgenerator.com/): Create tables and get export code for multiple formats
- [CMU RMarkdown guide (detailed)](http://www.stat.cmu.edu/~cshalizi/rmarkdown/)

Finally, here are a few more links for help with specific issues / customization:

- [Images and image sizing](http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/)
- [Pimp my RMD](https://holtzy.github.io/Pimp-my-rmd/): a guide for lots of cool features and customization options
- [RStudio R Markdown documentation](http://rmarkdown.rstudio.com/)
- [Producing html documents from `.R` scripts using `knitr::spin`](http://deanattali.com/2015/03/24/knitrs-best-hidden-gem-spin/)
- [Advanced RMD tips and tricks](https://docs.google.com/presentation/d/e/2PACX-1vRo1eXJtiwo6aTA8KZ2E-bUbv2GOonC2RIVk_5eWQ5y-ADXbRamBhHaa3w1vMW6BkEPOMJ13ZahSo8Q/embed?start=false&loop=true&delayms=30000&slide=id.p)
