---
title: "title"
author: "author"
output:
  html_document:
    toc: no
    toc_float: no
    theme: flatly
params:
    name: "John"
    number: 42
    animal: "Penguin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.retina = 3,
  fig.path = "figs/"
)
```

# Parameters

Did you know you can use parameters in your .Rmd files? Take a look at the YAML - notice the `params` starting on line 9. You can put any parameters you want there, and then use them later in the document.

For example, if I wanted to use the `name` parameter, I could insert it in a sentence like this: My name is `r params$name`!

Or I could use the `number` parameter like this: The answer to life, the universe, and everything is `r params$number`.

Now when you click on the "knit" button to renter this document, the parameter values will be used!

> Why do this?

Well, one common usage is if you want to create a templated document for some common purpose. You could create a report with parameters in it and then simply edit the `params` in the YAML to update it. This is common for things like annual reports where you want to keep everything the same but update the year, etc.


