# Install packages from CRAN - only need to do this once!
install.packages(c(
    'DT',
    'GGally',
    'HistData',
    'cowplot',
    'gganimate',
    'ggrepel',
    'ggrepel',
    'ggridges',
    'here',
    'hrbrthemes',
    'htmltools',
    'htmlwidgets',
    'janitor',
    'janitor',
    'kableExtra',
    'knitr',
    'leaflet',
    'lubridate',
    'magick',
    'mapproj',
    'maps',
    'palmerpenguins',
    'plotly',
    'quarto',
    'reactable',
    'reactablefmtr',
    'remotes',
    'rgeos',
    'rmarkdown',
    'rmdformats',
    'rnaturalearth',
    'rsconnect',
    'sf',
    'shiny',
    'shinyWidgets',
    'sparkline',
    'tidyverse',
    'viridis',
    'viridis',
    'waffle'
))

# Install remote (development) packages
remotes::install_github("mattcowgill/ggannotate")
remotes::install_github("ropensci/rnaturalearthhires")
remotes::install_github("ropensci/rnaturalearthdata")
