---
title: "Finding Data"
toc: true
toc-title: Table of contents
toc-location: left
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
source(here::here("R", "settings.R"))
```

The world is full of data, but sometimes finding it can be difficult. As a starting point, GW libraries has an excellent set of [Research Guides](https://libguides.gwu.edu/) that can be helpful. Depending on your research question, searching Google can also lead to good sources.

Here are some other resources:

# Large, search-able sites

Basically like running a Google search but only for data sets:

- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Quandl](https://www.quandl.com/): Over 2 million financial, economic, and social datasets.
- [Wharton Research Data Services](https://wrds-www.wharton.upenn.edu/): Single-point access to over 200 terabytes of data across multiple disciplines, including Finance, Marketing, and Economics.

# Websites

A collection of various websites that have lots of interesting datasets:

- ["Tidy Tuesday" challenges](https://github.com/rfordatascience/tidytuesday): Wide variety of datasets for data visualization practice. See many of the visualizations others have created [here](https://nsgrantham.shinyapps.io/tidytuesdayrocks/).
- ["Makeover Monday" challenges](http://www.makeovermonday.co.uk/data/): Wide variety of datasets for data visualization practice.
- [Tableau Community Forums](https://community.tableau.com/docs/DOC-10635): Sometimes you'll find some interesting datasets in here.
- ["Data is Beautiful" subreddit](https://www.reddit.com/r/dataisbeautiful/): Feed of user-generated data visualizations, though quality varies substantially.
- [Kaggle](https://www.kaggle.com/datasets): Hosts machine learning competitions, and as a result has lots of really interesting data sets open to the public.

# Packages

Many packages contain interesting datasets. If you can find a package with data, it will usually be nicely-formatted 😄

[Here](https://vincentarelbundock.github.io/Rdatasets/datasets.html) is a table of lots of packages that contain multiple dataset. Some of my favorites are:

- [`dslabs`](https://github.com/rafalab/dslabs)
- [`DAAG`](https://cran.r-project.org/web/packages/DAAG/index.html)
- [`MASS`](https://cran.r-project.org/web/packages/MASS/index.html)

In addition, some packages exclusively just contain datasets, such as:

- [fivethirtyeight](https://www.rdocumentation.org/packages/fivethirtyeight/versions/0.5.0): Datasets and code published by the data journalism website 'FiveThirtyEight', available at https://github.com/fivethirtyeight/data
- [gapminder](https://www.rdocumentation.org/packages/gapminder/)
- [babynames](https://github.com/hadley/babynames)
- [nycflights13](https://github.com/hadley/nycflights13)
- [fueleconomy](https://github.com/hadley/fueleconomy)
- [nasaweather](https://github.com/hadley/nasaweather)
- [usdanutrients](https://github.com/hadley/usdanutrients)

# Government-ish sources:

"Government-ish" because while some of these sites host government data, the sites themselves may or may not be affiliated with a government agency:

- [US Open Gov Data](https://www.data.gov/open-gov/): links to federal and non-federal sources in US and abroad
- [US City Open Data Census](http://us-city.census.okfn.org/): Open data from more than 100 U.S. cities.
- [Open Africa](https://africaopendata.org/)
- [EU Open Data Portal](https://data.europa.eu/euodp/en/home)
- [China data](https://www.ganghe.net/research/data): Various datasets on China posted by [Gang He](https://www.ganghe.net/).

# Energy data

Since I happen to work with energy data a lot, here's some common go-to sources:

- [China Energy Portal Statistics](https://chinaenergyportal.org/en/category/stats/): Loads of energy statistics from China.
- [U.S. Energy Information Administration](https://www.eia.gov/): from Wikipedia: the "principal agency of the U.S. Federal Statistical System responsible for collecting, analyzing, and disseminating energy information to promote sound policymaking, efficient markets, and public understanding of energy and its interaction with the economy and the environment. EIA programs cover data on coal, petroleum, natural gas, electric, renewable and nuclear energy. EIA is part of the U.S. Department of Energy."
- [Environmental Performance Index, Yale University](https://epi.envirocenter.yale.edu/): Ranks 163 countries on 25 performance indicators tracked across ten policy categories covering both environmental public health and ecosystem vitality. These indicators provide a gauge at a national government scale of how close countries are to established environmental policy goals.

# Spatial data

- http://freegisdata.rtwilson.com/
- https://data.nasa.gov/
- https://planet.parts/
- https://www.efi.int/knowledge/maps/forest
- https://land.copernicus.eu/
- https://maps.elie.ucl.ac.be/CCI/viewer/
- https://www.ecad.eu//dailydata/predefinedseries.php
- http://www.worldclim.org/version2
- https://www.geoportal.org/
- https://scihub.copernicus.eu/
- https://sedac.ciesin.columbia.edu/
- https://earthexplorer.usgs.gov/
